
server:
  servlet:
    context-path: /
  port: 8088

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/myWeb?characterEncoding=utf8&&useSSL=false
    username: root
    password: jia09210921
    driver-class-name: com.mysql.jdbc.Driver

  servlet:
    multipart:
      max-file-size: 400MB
      max-request-size: 400MB
      enabled: true
  session:
    redis:
      host: localhost
      port: 6379
      password:
      pool:
        max-active: 200       # ????????????????????
        max-idle: 10          # ???????????
        max-wait: -1          # ???????????????????????
        min-idle: 0           # ???????????
        timeout: 1000           # ??????????


file:
  location: C:/Users/lenovo/Desktop/store


